pub const SQL_KEYWORDS: &[&str] = &[
    // === DML/DQL 通用 ===
    "SELECT",
    "FROM",
    "WHERE",
    "GROUP BY",
    "ORDER BY",
    "HAVING",
    "LIMIT",
    "OFFSET",
    "INSERT INTO",
    "VALUES",
    "UPDATE",
    "SET",
    "DELETE FROM",
    "JOIN",
    "LEFT JOIN",
    "RIGHT JOIN",
    "INNER JOIN",
    "OUTER JOIN",
    "FULL JOIN",
    "CROSS JOIN",
    "ON",
    "USING",
    "UNION",
    "UNION ALL",
    "INTERSECT",
    "EXCEPT",
    "DISTINCT",
    "ALL",
    "AND",
    "OR",
    "NOT",
    "IN",
    "BETWEEN",
    "LIKE",
    "ILIKE",
    "IS NULL",
    "IS NOT NULL",
    "EXISTS",
    "ANY",
    "SOME",
    "ASC",
    "DESC",
    // === DDL ===
    "CREATE TABLE",
    "DROP TABLE",
    "ALTER TABLE",
    "TRUNCATE TABLE",
    "CREATE INDEX",
    "DROP INDEX",
    "CREATE VIEW",
    "DROP VIEW",
    "CREATE MATERIALIZED VIEW",
    "REFRESH MATERIALIZED VIEW",
    // === 表达式 / 控制流 ===
    "AS",
    "CASE",
    "WHEN",
    "THEN",
    "ELSE",
    "END",
    "IF",
    "IFNULL",
    "COALESCE",
    "NULLIF",
    // === 聚合 ===
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "GROUP_CONCAT",
    "STRING_AGG",
    "ARRAY_AGG",
    // === 日期 / 字符串 ===
    "NOW",
    "CURRENT_TIMESTAMP",
    "CURRENT_DATE",
    "DATE",
    "DATE_FORMAT",
    "DATEDIFF",
    "DATE_TRUNC",
    "EXTRACT",
    "CONCAT",
    "SUBSTRING",
    "LENGTH",
    "TRIM",
    "UPPER",
    "LOWER",
    "CAST",
    "CONVERT",
    // === 字面量 ===
    "TRUE",
    "FALSE",
    "NULL",
    // === PostgreSQL 特有（mysql 不会用，但补齐到 PG 用户也省心；下拉里多几个无害）===
    "RETURNING",
    "ON CONFLICT",
    "DO UPDATE",
    "DO NOTHING",
    "WITH",
    "WITH RECURSIVE",
    "LATERAL",
    "SERIAL",
    "BIGSERIAL",
    "GENERATED ALWAYS AS",
    "GENERATED BY DEFAULT AS IDENTITY",
    "ARRAY",
    "FOR UPDATE",
    "FOR SHARE",
    // === MySQL 特有（PG 不会用）===
    "ON DUPLICATE KEY UPDATE",
];

/// SQL 系统内置库（MySQL + PostgreSQL union；默认隐藏；下拉/表树排序时下沉）
pub const SYSTEM_SCHEMAS: &[&str] = &[
    // MySQL
    "mysql",
    "performance_schema",
    "sys",
    // PostgreSQL
    "pg_catalog",
    "pg_toast",
    // 共用（MySQL + PG 都有）
    "information_schema",
];

/// 大小写无关地判断库名是否系统内置
///
/// PG 的 `pg_temp_*` / `pg_toast_temp_*` 是动态会话临时 schema，按前缀过滤
pub fn is_system_schema(name: &str) -> bool {
    let lower = name.to_ascii_lowercase();
    if SYSTEM_SCHEMAS
        .iter()
        .any(|s| s.eq_ignore_ascii_case(&lower))
    {
        return true;
    }
    lower.starts_with("pg_temp_") || lower.starts_with("pg_toast_temp_")
}
